#!/bin/bash

set -e -o pipefail

# Simple script to generate a simple text-based sitemap. Don't use XML since
# it's kind of overkill for a simple site with lots of static HTML pages.
# We also exclude the redirect.html since it's not really useful to crawl.
echo "https://macvim.org/docs/"
for f in *.html; do
    if [[ "$f" != "redirect.html" && "$f" != "index.html" ]]; then
        echo "https://macvim.org/docs/$f"
    fi
done
